name: CI and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Need previous commit to check version changes
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Install dependencies
      if: success()
      run: bun install
    
    - name: Run typecheck
      id: typecheck
      if: success()
      run: bun run typecheck
    
    - name: Run build
      id: build
      if: success()
      run: bun run build
    
    - name: Run tests (attempt 1)
      id: test1
      if: success()
      continue-on-error: true
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: bun test --timeout 30000
    
    - name: Run tests (attempt 2)
      id: test2
      if: steps.test1.outcome == 'failure'
      continue-on-error: true
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: bun test --timeout 30000
    
    - name: Run tests (attempt 3)
      id: test3
      if: steps.test1.outcome == 'failure' && steps.test2.outcome == 'failure'
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: bun test --timeout 30000
    
    - name: Check tests passed
      id: tests_passed
      if: steps.test1.outcome == 'success' || steps.test2.outcome == 'success' || steps.test3.outcome == 'success'
      run: |
        echo "Tests passed!"
        echo "tests_passed=true" >> $GITHUB_OUTPUT
    
    - name: Check version change
      id: version_check
      if: steps.tests_passed.outputs.tests_passed == 'true'
      run: |
        # Get current version from package.json
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        
        # Get previous version from the previous commit
        git show HEAD~1:package.json > previous-package.json 2>/dev/null || echo '{"version":"0.0.0"}' > previous-package.json
        PREVIOUS_VERSION=$(node -p "require('./previous-package.json').version")
        echo "Previous version: $PREVIOUS_VERSION"
        
        # Check if version changed
        if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
          echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
          echo "version_changed=true" >> $GITHUB_OUTPUT
        else
          echo "Version unchanged"
          echo "version_changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Publish to npm
      if: steps.tests_passed.outputs.tests_passed == 'true' && steps.version_check.outputs.version_changed == 'true' && github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public